[book]
authors = ["Ahmed Khaled"]
title = "Ahmed Khaled Resources"
description = "My name is Ahmed Khaled a computer hobbyist and a DevOps Engineer. This is my resources list that I collect regulary to help me in my daily work and personal hobbies and projects."
language = "en"
multilingual = false
src = "src"
