#!/usr/bin/env bash

COMMIT_NAME=$1
OLD_DIR="$PWD"

git worktree add /tmp/book gh-pages
mdbook build
rm -rf /tmp/book/* # this won't delete the .git directory
cp -a book/* /tmp/book/
cd /tmp/book
git add -A
git commit -m "$COMMIT_NAME"
git push origin gh-pages
cd "$PWD"

git add -A
git commit -m "$COMMIT_NAME"
git push origin master