#!/usr/bin/env bash

COMMIT_NAME=$1
OLD_DIR="$PWD"

echo "== gh-pages BRANCH =="
git worktree add /tmp/book gh-pages
mdbook build
rm -rf /tmp/book/* # this won't delete the .git directory
cp -a book/* /tmp/book/
cd /tmp/book
git add -A
git commit -m "$COMMIT_NAME"
git push origin gh-pages

cd "$OLD_DIR"

echo "== MASTER BRANCH =="
git add -A
git commit -m "$COMMIT_NAME"
git push origin master

git worktree remove /tmp/book